apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cattle-monitoring-system

resources:
  - ./resources/namespace.yaml

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: kube-prometheus-stack
    releaseName: rancher-monitoring
    valuesFile: values.yaml
    namespace: cattle-monitoring-system
    includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-options: "ServerSideApply=true"