apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cattle-monitoring-system

resources:
  - ./resources/namespace.yaml

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: kube-prometheus-stack
    releaseName: rancher-monitoring
    valuesFile: values.yaml
    includeCRDs: true
    namespace: cattle-monitoring-system

# patches:
#   - target:
#       kind: ServiceMonitor
#       labelSelector: "app.kubernetes.io/instance=rancher-monitoring"
#     patch: |-
#       - op: add
#         path: /spec/endpoints/0/metricRelabelings
#         value:
#           - sourceLabels: [__name__]
#             regex: "(^go_.*|^promhttp_.*|^prometheus_.*|^target_info$)"
#             action: drop

commonAnnotations:
  argocd.argoproj.io/sync-options: "ServerSideApply=true"