apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cattle-monitoring-system

resources:
  - ./resources/namespace.yaml

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: kube-prometheus-stack
    releaseName: rancher-monitoring
    valuesFile: values.yaml
    includeCRDs: true
    namespace: cattle-monitoring-system

patches:
  - target:
      kind: ServiceMonitor
      labelSelector: 'release=rancher-monitoring'
    path: patches/init-metrics.yaml

  - target:
      kind: ServiceMonitor
      labelSelector: 'app=kube-prometheus-stack-kubelet'
    path: patches/append-metrics.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: 'ServerSideApply=true'
